Add new tools: Clair, Snyk, Grype
theredguild/container-sec-tools pull request #15
Opened 2024-10-03 20:01 UTC by reynico

2024-10-03 20:08 UTC, reynico commented
wrong upstream heh

2024-10-03 23:34 UTC, mattaereal requested changes
I installed grype and snyk differently. Tried to suggest small changes via gh's UI but horrible experience. 

A few PRs after this I successfully installed them both las follows:
`RUN pnpm install -g snyk`
`RUN curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin`

2024-10-03 23:34 UTC, mattaereal commented on Dockerfile
> +RUN ARCH=$(dpkg --print-architecture) \
```suggestion
RUN curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
```

2024-10-03 23:34 UTC, mattaereal commented on Dockerfile
> +    && wget -q https://github.com/anchore/grype/releases/download/v0.81.0/grype_0.81.0_linux_$ARCH.deb \
```suggestion
```

2024-10-03 23:34 UTC, mattaereal commented on Dockerfile
> +    && sudo dpkg -i grype_0.81.0_linux_$ARCH.deb \
```suggestion
```

2024-10-03 23:34 UTC, mattaereal commented on Dockerfile
> +    && rm grype_0.81.0_linux_$ARCH.deb
```suggestion
```

2024-10-03 23:34 UTC, mattaereal commented on Dockerfile
> +RUN ARCH=$(dpkg --print-architecture) \
```suggestion
RUN pnpm install -g snyk
```
I'd suggest installing it directly from the repo, and delete the rest

2024-10-03 23:52 UTC, reynico commented on Dockerfile
> +    && rm grype_0.81.0_linux_$ARCH.deb
y that?

2024-10-03 23:57 UTC, reynico commented
> I installed grype and snyk differently. Tried to suggest small changes via gh's UI but horrible experience.
> 
> A few PRs after this I successfully installed them both las follows: `RUN pnpm install -g snyk` `RUN curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin`

gotcha! just addressed the comments and committed a last fix to the suggestions. CI is passing as expected so I think this is good to go

2024-10-04 15:24 UTC, mattaereal approved these changes

2024-10-04 15:24 UTC, merged